gui:
  timeFormat: "02 Jan 06 15:04"
  # Use side-by-side diffs when the screen is wide enough
  sideBySideDiff: auto

git:
  pagers:
    - colorArg: always
      pager: >
        delta --paging never --syntax-theme none --context 10 --line-numbers
        --file-style yellow
        --file-decoration-style "yellow ul"
        --hunk-header-decoration-style "yellow box"
        --hunk-header-file-style yellow
        --hunk-header-line-number-style yellow
        --inline-hint-style yellow

  commitPrefix:
    - pattern: "(\\w+)[-_](\\d+).*"
      replace: '[$1-$2] '

  # https://github.com/jesseduffield/lazygit/issues/3758 for signing commits
  overrideGpg: true

# Custom commands to make PR workflows faster
customCommands:
  - key: 'C'
    command: "git diff {{.SelectedLocalBranch.Name}}...HEAD"
    context: 'localBranches'
    description: 'Diff against selected branch'
    output: log
  - key: 'P'
    command: "git diff main...HEAD"
    context: 'files'
    description: 'Diff current branch against main (PR view)'
    output: log
  - key: 'O'
    command: "gh pr view --web"
    context: 'global'
    description: 'Open current PR on GitHub'
